name: Build and Release

on:
  push:
    tags:
      - 'v*'
jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: 3.9
          spec: 'src/notepad.py'
          upload_exe_with_name: 'Notepad'
          options: --onefile, --name "Notepad", --windowed,
      - uses: actions/download-artifact@v4
        with:
          name: Notepad
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Notepad.zip
          asset_name: Notepad.zip
          asset_content_type: application/zip
