name: Build and Release

on:
  push:
    tags:
      - 'v*'
jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: 3.9
          spec: 'src/notepad.py'
          upload_exe_with_name: '../dist/Notepad.exe'
          options: --onefile, --name "Notepad", --windowed, 
